
"""
Hertel-Mehlhorn convex decomposition algorithm.

Pipeline:
  1. Ear-clip triangulation  -> list of triangles
  2. Build adjacency graph   -> triangles sharing a diagonal
  3. Greedy diagonal removal -> merge if result stays convex
  4. Return convex polygons

All polygons are represented as lists of (x, y) tuples in CCW order.
"""

"""
This solution has been generated by Claude,
it serves as a reference implementation of the Hertel-Mehlhorn convex decomposition algorithm.

This solution has been reimplemented by me to be more readable and maintainable, and to be used as a reference for the TPP solver.
"""

from __future__ import annotations
import math


# ---------------------------------------------------------------------------
# Geometry primitives
# ---------------------------------------------------------------------------

def cross(o: tuple, a: tuple, b: tuple) -> float:
	"""Signed area × 2 of triangle (o, a, b). Positive = CCW."""
	return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])


def is_ccw(polygon: list[tuple]) -> bool:
	"""True if polygon vertices are in counter-clockwise order."""
	return signed_area(polygon) > 0


def signed_area(polygon: list[tuple]) -> float:
	n = len(polygon)
	area = 0.0
	for i in range(n):
		x0, y0 = polygon[i]
		x1, y1 = polygon[(i + 1) % n]
		area += (x0 * y1 - x1 * y0)
	return area / 2.0


def ensure_ccw(polygon: list[tuple]) -> list[tuple]:
	if not is_ccw(polygon):
		return polygon[::-1]
	return polygon


def is_convex_vertex(prev: tuple, curr: tuple, next_: tuple) -> bool:
	"""True if the turn at curr (prev->curr->next) is left (CCW), i.e. not reflex."""
	return cross(prev, curr, next_) >= 0


def is_convex_polygon(polygon: list[tuple]) -> bool:
	"""True if polygon is convex (all turns are CCW for a CCW polygon)."""
	n = len(polygon)
	if n < 3:
		return False
	for i in range(n):
		prev = polygon[(i - 1) % n]
		curr = polygon[i]
		next_ = polygon[(i + 1) % n]
		if cross(prev, curr, next_) < -1e-10:
			return False
	return True


def point_in_triangle(p: tuple, a: tuple, b: tuple, c: tuple) -> bool:
	"""True if point p is strictly inside triangle (a, b, c) — CCW winding."""
	d1 = cross(a, b, p)
	d2 = cross(b, c, p)
	d3 = cross(c, a, p)
	has_neg = (d1 < 0) or (d2 < 0) or (d3 < 0)
	has_pos = (d1 > 0) or (d2 > 0) or (d3 > 0)
	return not (has_neg and has_pos)


def segments_properly_intersect(a: tuple, b: tuple, c: tuple, d: tuple) -> bool:
	"""True if segment ab properly intersects segment cd (not at endpoints)."""
	d1 = cross(c, d, a)
	d2 = cross(c, d, b)
	d3 = cross(a, b, c)
	d4 = cross(a, b, d)
	if ((d1 > 0 and d2 < 0) or (d1 < 0 and d2 > 0)) and \
	   ((d3 > 0 and d4 < 0) or (d3 < 0 and d4 > 0)):
		return True
	return False


# ---------------------------------------------------------------------------
# Step 1 — Ear-clip triangulation
# ---------------------------------------------------------------------------

def is_ear(polygon: list[tuple], i: int) -> bool:
	"""
	Vertex i is an ear if:
	  - the turn at i is convex (left turn in CCW polygon)
	  - no other polygon vertex lies inside the triangle (prev, i, next)
	"""
	n = len(polygon)
	prev = polygon[(i - 1) % n]
	curr = polygon[i]
	next_ = polygon[(i + 1) % n]

	if cross(prev, curr, next_) <= 0:
		return False  # reflex vertex, not an ear

	for j in range(n):
		if j in ((i - 1) % n, i, (i + 1) % n):
			continue
		if point_in_triangle(polygon[j], prev, curr, next_):
			return False
	return True


def triangulate(polygon: list[tuple]) -> list[tuple[tuple, tuple, tuple]]:
	"""
	Ear-clipping triangulation. O(n²).
	Returns a list of triangles as 3-tuples of (x,y) points.
	"""
	poly = list(ensure_ccw(polygon))
	triangles = []

	while len(poly) > 3:
		n = len(poly)
		ear_found = False
		for i in range(n):
			if is_ear(poly, i):
				prev = poly[(i - 1) % n]
				curr = poly[i]
				next_ = poly[(i + 1) % n]
				triangles.append((prev, curr, next_))
				poly.pop(i)
				ear_found = True
				break
		if not ear_found:
			# Numerical issues — clip anyway to avoid infinite loop
			triangles.append((poly[0], poly[1], poly[2]))
			poly.pop(1)

	triangles.append((poly[0], poly[1], poly[2]))
	return triangles


# ---------------------------------------------------------------------------
# Step 2 — Build dual adjacency graph
# ---------------------------------------------------------------------------

def shared_diagonal(
	tri_a: list[tuple], tri_b: list[tuple]
) -> tuple[tuple, tuple] | None:
	"""
	Return the shared edge (diagonal) between two triangles, or None.
	An edge is shared if both its endpoints appear in both triangles.
	"""
	set_a = set(tri_a)
	set_b = set(tri_b)
	shared = set_a & set_b
	if len(shared) == 2:
		pts = list(shared)
		return (pts[0], pts[1])
	return None

# ---------------------------------------------------------------------------
# Step 3 — Merge two polygons along their shared diagonal
# ---------------------------------------------------------------------------

def merge_polygons(
	poly_a: list[tuple], poly_b: list[tuple], diag: tuple[tuple, tuple]
) -> list[tuple] | None:
	"""
	Merge poly_a and poly_b by removing their shared diagonal.
	Returns the merged polygon in CCW order, or None if inputs don't share diag.

	In a CCW decomposition the shared edge appears as u->v in one polygon
	and v->u in the other.  We find which polygon has u->v and which has v->u,
	then splice them together.
	"""
	u, v = diag

	try:
		ia_u = poly_a.index(u)
		ia_v = poly_a.index(v)
		ib_u = poly_b.index(u)
		ib_v = poly_b.index(v)
	except ValueError:
		return None

	n_a, n_b = len(poly_a), len(poly_b)

	# Determine which polygon has the u->v edge and which has v->u
	# (in a valid CCW decomposition exactly one of each holds)
	a_has_uv = (ia_u + 1) % n_a == ia_v   # poly_a: u -> v
	a_has_vu = (ia_v + 1) % n_a == ia_u   # poly_a: v -> u
	b_has_uv = (ib_u + 1) % n_b == ib_v
	b_has_vu = (ib_v + 1) % n_b == ib_u

	if a_has_uv and b_has_vu:
		# poly_a: ...->u->v->...   poly_b: ...->v->u->...
		# Merged: walk poly_a from v (skip v->...->u), then walk poly_b from u (skip u->...->v)
		merged = []
		i = ia_v
		while True:
			merged.append(poly_a[i])
			i = (i + 1) % n_a
			if i == ia_u:
				break
		i = ib_u
		while True:
			merged.append(poly_b[i])
			i = (i + 1) % n_b
			if i == ib_v:
				break
		return merged if len(merged) >= 3 else None

	elif a_has_vu and b_has_uv:
		# Symmetric: poly_a has v->u, poly_b has u->v
		merged = []
		i = ib_v
		while True:
			merged.append(poly_b[i])
			i = (i + 1) % n_b
			if i == ib_u:
				break
		i = ia_u
		while True:
			merged.append(poly_a[i])
			i = (i + 1) % n_a
			if i == ia_v:
				break
		return merged if len(merged) >= 3 else None

	return None


# ---------------------------------------------------------------------------
# Step 4 — Hertel-Mehlhorn greedy merging
# ---------------------------------------------------------------------------

def hertel_mehlhorn(polygon: list[tuple]) -> list[list[tuple]]:
	"""
	Hertel-Mehlhorn convex decomposition.

	Args:
		polygon: Simple polygon as CCW list of (x, y) tuples.

	Returns:
		List of convex polygons covering the input.
	"""
	polygon = ensure_ccw(polygon)

	# Degenerate / already convex
	if is_convex_polygon(polygon):
		return [polygon]

	# Step 1: triangulate
	triangles = triangulate(polygon)
	pieces: list[list[tuple]] = [list(t) for t in triangles]

	# Step 2+3: repeatedly try to merge adjacent pieces
	# We keep iterating until no merge is possible in a full pass
	changed = True
	while changed:
		changed = False
		n = len(pieces)
		merged_flags = [False] * n
		new_pieces = []

		i = 0
		while i < len(pieces):
			if merged_flags[i]:
				i += 1
				continue
			merged_any = False
			for j in range(i + 1, len(pieces)):
				if merged_flags[j]:
					continue
				diag = shared_diagonal(pieces[i], pieces[j])
				if diag is None:
					continue
				candidate = merge_polygons(pieces[i], pieces[j], diag)
				if candidate is None:
					continue
				if is_convex_polygon(candidate):
					new_pieces.append(candidate)
					merged_flags[i] = True
					merged_flags[j] = True
					merged_any = True
					changed = True
					break
			if not merged_any and not merged_flags[i]:
				new_pieces.append(pieces[i])
			i += 1

		pieces = new_pieces

	return pieces


# ---------------------------------------------------------------------------
# Quick test
# ---------------------------------------------------------------------------

if __name__ == "__main__":

	polygon = [
		(0, 0), (2, 0), (2, 1), (1.5, 1), (1.5, 2), (2, 2), (2, 3), (0, 3)		
	]

	parts = hertel_mehlhorn(polygon)

	print(f"Input: {len(polygon)} vertices")
	print(f"Output: {len(parts)} convex pieces")
	for i, p in enumerate(parts):
		print(f"  [{i}] {p}")
		assert is_convex_polygon(p), f"Piece {i} is not convex!"
	print("All pieces verified convex.")

	import matplotlib.pyplot as plt

	plt.figure(figsize=(6, 6))
	# Plot original polygon
	px, py = zip(*polygon)
	plt.fill(px, py, color="lightgray", edgecolor="black", alpha=0.5, label="Input Polygon")
	# Plot convex pieces
	for i, part in enumerate(parts):
		px, py = zip(*part)
		plt.fill(px, py, alpha=0.5, label=f"Piece {i}")
	plt.legend()
	plt.title("Hertel-Mehlhorn Convex Decomposition")
	plt.axis("equal")
	plt.show()